server:
  port: 8083
  servlet:
    context-path: /mt
spring:
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL;
    #url: jdbc:h2:file:E:/MT_DB;MODE=PostgreSQL;AUTO_SERVER=TRUE;
    url: jdbc:h2:file:./src/main/resources/MT_DB;MODE=PostgreSQL;AUTO_SERVER=TRUE;
    username: mt
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false